# Generated by Django 3.1.10 on 2023-05-04 05:05

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_genshinpromobot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genshinpromobot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
    ]
