# Generated by Django 3.1.10 on 2023-06-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20230504_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='genshinpromobot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='genshinpromobot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
