# Generated by Django 3.1.10 on 2023-06-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20230623_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genshinpromobot',
            name='active',
        ),
    ]
