# Generated by Django 3.2 on 2021-04-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
