# Generated by Django 3.2 on 2021-04-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
