# Generated by Django 3.2 on 2021-04-22 23:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0007_auto_20210422_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribedGames',
            new_name='SubscribedGame',
        ),
    ]
