# Generated by Django 3.2 on 2021-04-23 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0008_rename_subscribedgames_subscribedgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedgame',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
