# Generated by Django 3.1.8 on 2021-05-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210515_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hash_value',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
