# Generated by Django 3.1.8 on 2021-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_game_last_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='check_frequency_hours',
            field=models.IntegerField(default=4),
        ),
    ]
