# Generated by Django 3.1.10 on 2021-06-19 02:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20210619_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to=''),
        ),
    ]
