# Generated by Django 3.1.10 on 2021-06-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20210619_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedgame',
            name='subGames',
            field=models.TextField(blank=True, default=''),
        ),
    ]
