# Generated by Django 3.1.10 on 2021-06-19 05:46

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20210619_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='check_frequency_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, quality=0, size=[500, 500], upload_to=''),
        ),
    ]
