# Generated by Django 3.1.10 on 2021-06-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20210619_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_check',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
