# Generated by Django 3.1.10 on 2021-06-20 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_auto_20210619_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
    ]
